[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
event_manager = "2YSF7QNdZ46wqy6njMSTz85dAWo97XEGPTNCf6ULV71o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/fran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
